//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AG.COM.SDM.Config {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonVariablesKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonVariablesKeys() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AG.COM.SDM.Config.CommonVariablesKeys", typeof(CommonVariablesKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 MinioServerAccess 的本地化字符串。
        /// </summary>
        public static string MinioServerAccess {
            get {
                return ResourceManager.GetString("MinioServerAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinioServerBucket 的本地化字符串。
        /// </summary>
        public static string MinioServerBucket {
            get {
                return ResourceManager.GetString("MinioServerBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinioServerPassWord 的本地化字符串。
        /// </summary>
        public static string MinioServerPassWord {
            get {
                return ResourceManager.GetString("MinioServerPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinioServerURL 的本地化字符串。
        /// </summary>
        public static string MinioServerURL {
            get {
                return ResourceManager.GetString("MinioServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OLEConnColl 的本地化字符串。
        /// </summary>
        public static string OLEConnColl {
            get {
                return ResourceManager.GetString("OLEConnColl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OLEDataBase 的本地化字符串。
        /// </summary>
        public static string OLEDataBase {
            get {
                return ResourceManager.GetString("OLEDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OLEDbType 的本地化字符串。
        /// </summary>
        public static string OLEDbType {
            get {
                return ResourceManager.GetString("OLEDbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OLEPassword 的本地化字符串。
        /// </summary>
        public static string OLEPassword {
            get {
                return ResourceManager.GetString("OLEPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OLEPort 的本地化字符串。
        /// </summary>
        public static string OLEPort {
            get {
                return ResourceManager.GetString("OLEPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OLEServer 的本地化字符串。
        /// </summary>
        public static string OLEServer {
            get {
                return ResourceManager.GetString("OLEServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OLEUser 的本地化字符串。
        /// </summary>
        public static string OLEUser {
            get {
                return ResourceManager.GetString("OLEUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProjectPath 的本地化字符串。
        /// </summary>
        public static string ProjectPath {
            get {
                return ResourceManager.GetString("ProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpatialDatabase 的本地化字符串。
        /// </summary>
        public static string SpatialDatabase {
            get {
                return ResourceManager.GetString("SpatialDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpatialDbType 的本地化字符串。
        /// </summary>
        public static string SpatialDbType {
            get {
                return ResourceManager.GetString("SpatialDbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpatialInstance 的本地化字符串。
        /// </summary>
        public static string SpatialInstance {
            get {
                return ResourceManager.GetString("SpatialInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpatialPassword 的本地化字符串。
        /// </summary>
        public static string SpatialPassword {
            get {
                return ResourceManager.GetString("SpatialPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpatialPort 的本地化字符串。
        /// </summary>
        public static string SpatialPort {
            get {
                return ResourceManager.GetString("SpatialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpatialServer 的本地化字符串。
        /// </summary>
        public static string SpatialServer {
            get {
                return ResourceManager.GetString("SpatialServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpatialUser 的本地化字符串。
        /// </summary>
        public static string SpatialUser {
            get {
                return ResourceManager.GetString("SpatialUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StyleFiles 的本地化字符串。
        /// </summary>
        public static string StyleFiles {
            get {
                return ResourceManager.GetString("StyleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AM_LOGGER 的本地化字符串。
        /// </summary>
        public static string SYSLogger {
            get {
                return ResourceManager.GetString("SYSLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AM_SYSTEM_MainMenu 的本地化字符串。
        /// </summary>
        public static string SYSMainMenu {
            get {
                return ResourceManager.GetString("SYSMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AM_SYSTEM_STARTITEM 的本地化字符串。
        /// </summary>
        public static string SYSStartItem {
            get {
                return ResourceManager.GetString("SYSStartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AM_SYSTEM_User 的本地化字符串。
        /// </summary>
        public static string SYSUser {
            get {
                return ResourceManager.GetString("SYSUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UIDesignLoadFrom 的本地化字符串。
        /// </summary>
        public static string UIDesignLoadFrom {
            get {
                return ResourceManager.GetString("UIDesignLoadFrom", resourceCulture);
            }
        }
    }
}
